### ISSUE TITLE
disam() not disarm()?

### ISSUE THREAD

**Issue by ibroheem** [DmitryOlshansky/photon#23]
https://github.com/DmitryOlshansky/photon/blob/acfe17d001b590381f34587b7f0db7a4726d7bd9/src/photon/linux/core.d#L101

**Comment by DmitryOlshansky** [comment]
Yeah, looks like a typo.

пн, 30 дек. 2019 г. в 18:57, Ибраги́м M <notifications@github.com>:

**Comment by DmitryOlshansky** [comment]
Fixed
